### ISSUE TITLE
Student Data Management System

### ISSUE THREAD

**Issue by LoNeWoLf003** [SamarthTMSL/Python-Games-and-Projects#53]
I have made a Student Data Management project using Python language. It works with the help of tkinter and various other libraries. Not only that, it also stores the data using sqlite3 library, meaning you would not lose the data even after you close the project. You can re-run the project and you will get the data you stored earlier. Basic CRUD operations are also included here.

Please allow me to add the aforementioned project for Hacktoberfest 2022!

**Comment by SamarthTMSL** [comment]
@LoNeWoLf003 Make a pr and add it
